#!/bin/bash
set -eu

# ----------------------------------------------------------
# 設定 AWS EC2
# ----------------------------------------------------------

TYPE="EC2"

# awscliで使用するプロファイル
# `cat ~/.aws/config` で確認できる
# https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/cli-configure-profiles.html
export AWS_DEFAULT_PROFILE='my-profile-191213'

# インスタンスID
INSTANCE_ID='i-01234567890123456'

# ユーザ名
SSH_USERNAME=ec2-user

# SSH用 user@host を設定(user@host)
set_ssh_con() { SSH_CON="$SSH_USERNAME@$INSTANCE_PUBLIC_IPADDR" }

# マウントするホームディレクトリ
MOUNT_HOMEDIR=/home/$SSH_USERNAME

# ----------------------------------------------------------
# 実行
# ----------------------------------------------------------
# 自分自身のいるパスを得る 
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# cloud-instance-starter.sh を読み込む(フルパス)
source "$BASEDIR/cloud-instance-starter.sh"
run $@
